version: "3"

networks:
  ipms_network:

volumes:
  ipms_volume:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ipms_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - ipms_network

  mysql:
    image: mysql:8
    container_name: ipms_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ipms_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ipms
      MYSQL_USER: ipms
      MYSQL_PASSWORD: ipms
      MYSQL_ROOT_PASSWORD: ipms
      SERVICE_NAME: mysql
    networks:
      - ipms_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ipms_php
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - ipms_network

  redis:
    image: redis:alpine
    container_name: ipms_redis
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - ipms_volume:/var/lib/redis
    networks:
      - ipms_network
